# Generated by Django 5.2.15 on 2026-06-15 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joined_at', models.DateField()),
                ('left_at', models.DateField(blank=True, null=True)),
                ('member_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('GUEST', 'Guest')], default='PERMANENT', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups_app.group')),
            ],
        ),
    ]
