# Generated by Django 5.2.15 on 2026-06-15 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_app', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('SETTLEMENT', 'Settlement'), ('REFUND', 'Refund'), ('DEPOSIT', 'Deposit')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('split_type', models.CharField(choices=[('EQUAL', 'Equal'), ('UNEQUAL', 'Unequal'), ('PERCENTAGE', 'Percentage'), ('SHARE', 'Share')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_app.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_app.membership')),
            ],
        ),
    ]
