# Generated by Django 5.2.15 on 2026-06-15 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0002_membership'),
        ('transactions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('owed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_app.membership')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions_app.transaction')),
            ],
        ),
    ]
